# permissions for end users to view certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubermatic-certmanager
    app.kubernetes.io/managed-by: kustomize
  name: certificate-viewer-role
rules:
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certs.k8c.io
  resources:
  - certificates/status
  verbs:
  - get
